[package]
name = "batch_process"
version = "0.0.0"

[addresses]
aptos_address = "0x827b56914a808d9f638252cd9b3c1229a2c2bc606eb4f70f53c741350f1dea0e"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "testnet" }
